Revert "ARM: dts: msm: Add speedbin four support for QRB5165n"
This reverts commit e6673e042f9dab6c3b694f633614edb6583efa13.

Required to resolve duplicate definitions leading to build errors
arch/arm64/boot/dts/vendor/qcom/kona-moto-base-v2.1.dtb: ERROR (duplicate_node_names):
Duplicate node name /soc/qcom,kgsl-3d0@3d00000/qcom,gpu-pwrlevel-bins/qcom,gpu-pwrlevels-4
ERROR: Input tree has errors, aborting (use -f to force output)

Change-Id: I539e08e67763ee4e25d7744fa06900baf51e7d79
Signed-off-by: Srihari Sathyanarayana <sriharis@motorola.com>
Reviewed-on: https://gerrit.mot.com/2067276
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Submit-Approved: Jira Key
Tested-by: Jira Key
Reviewed-by: Xu Zhang <zhangxu21@lenovo.com>