ets_fps_mmi: Add missing fingerprint sensor pose config
kernel/motorola/sm7250/drivers/input/fingerprint/ets_fps_mmi/ets_navi_input.c:96:5: error: 'CONFIG_INPUT_EGISTEC_FPS_POSE' is not defined, evaluates t
o 0 [-Werror,-Wundef]
   96 | #if CONFIG_INPUT_EGISTEC_FPS_POSE==0
      |     ^

Change-Id: Ida7dc6056ee7c7d3e6a110fd47effe7f1d795c20
Signed-off-by: Pranav Vashi <neobuddy89@gmail.com>