Revert "(CR) qc3p:enable qc3p only at prc sku"
Revert "(CR) qc3p:enable qc3p only at prc sku"

this change is breaking R builds for Racer_turbo that are also used on S.

/localrepo/hudson/workspace/RPB31_Racer_turbo-retail_userdebug_mr_r-qsm8250_test-keys_continuous/platform/kernel/msm-4.19/drivers/power/supply/qcom/smb5-lib.c:2766:12: error: no member named 'mmi_qc3p_support' in 'struct smb_charger'
                if(!chg->mmi_qc3p_support) {
                    ~~~  ^
1 error generated.

This reverts commit f7798341584ba9dbd67b15a79c0eb8305e528532.

Change-Id: I73fced7b4908055c1afec26f8c0947f114ad476f
Reviewed-on: https://gerrit.mot.com/1994681
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Reviewed-by: Nagarathna Kodandaram <cnfk37@motorola.com>
Reviewed-by: Sergio Vilela <sergiosv@motorola.com>
SME-Granted: Sergio Vilela <sergiosv@motorola.com>
Submit-Approved: Sergio Vilela <sergiosv@motorola.com>
Tested-by: Sergio Vilela <sergiosv@motorola.com>